app_version: 1.2.25
capabilities: []
categories:
- media
- productivity
changelog_url: https://github.com/ShaneIsrael/fireshare/compare/v1.2.24...v1.2.25
description: Share your game clips, videos, or other media via unique links.
home: https://github.com/ShaneIsrael/fireshare
host_mounts: []
icon: https://raw.githubusercontent.com/ShaneIsrael/fireshare/refs/heads/main/app/client/src/assets/logo.png
keywords:
- file-sharing
- media-server
- self-hosted
- video-sharing
lib_version: 2.1.28
lib_version_hash: a10ff230ce45e138b733b395843841e33e85be87c39fa5e61401aa781828d0a7
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: fireshare
run_as_context:
- description: Fireshare runs as specified user with configurable UID/GID.
  gid: 1000
  group_name: fireshare
  uid: 1000
  user_name: fireshare
screenshots:
- https://github.com/ShaneIsrael/fireshare/blob/main/.github/images/card-view.png
sources:
- https://github.com/ShaneIsrael/fireshare
title: Fireshare
train: community
version: 1.0.0
