resources:
  limits:
    cpus: 2.0
    memory: 4096

fireshare:
  admin_username: admin
  admin_password: changeme
  secret_key: supersecretkey
  minutes_between_video_scans: 5
  thumbnail_video_location: 50
  domain: localhost
  user_id: 1000
  group_id: 1000
  additional_envs: []

run_as:
  user: 1000
  group: 1000

network:
  web_port:
    bind_mode: published
    port_number: 8080

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  processed:
    type: ix_volume
    ix_volume_config:
      dataset_name: processed
      create_host_path: true
  videos:
    type: ix_volume
    ix_volume_config:
      dataset_name: videos
      create_host_path: true
  additional_storage: []
