{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.fireshare_container_name, "image") %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.fireshare.user_id, "gid": values.fireshare.group_id, "mode": "check"} %}

{% do c1.set_user(values.fireshare.user_id, values.fireshare.group_id) %}
{% do c1.add_port(values.network.web_port) %}
{% do c1.environment.add_env("TZ", values.TZ) %}
{% do c1.environment.add_env("ADMIN_USERNAME", values.fireshare.admin_username) %}
{% do c1.environment.add_env("ADMIN_PASSWORD", values.fireshare.admin_password) %}
{% do c1.environment.add_env("SECRET_KEY", values.fireshare.secret_key) %}
{% do c1.environment.add_env("MINUTES_BETWEEN_VIDEO_SCANS", values.fireshare.minutes_between_video_scans) %}
{% do c1.environment.add_env("THUMBNAIL_VIDEO_LOCATION", values.fireshare.thumbnail_video_location) %}
{% do c1.environment.add_env("DOMAIN", values.fireshare.domain) %}
{% do c1.environment.add_env("PUID", values.fireshare.user_id) %}
{% do c1.environment.add_env("PGID", values.fireshare.group_id) %}
{% do c1.environment.add_user_envs(values.fireshare.additional_envs) %}

{% do c1.add_storage("/data", values.storage.data) %}
{% do c1.add_storage("/processed", values.storage.processed) %}
{% do c1.add_storage("/videos", values.storage.videos) %}

{% do perm_container.add_or_skip_action("/data", values.storage.data, perms_config) %}
{% do perm_container.add_or_skip_action("/processed", values.storage.processed, perms_config) %}
{% do perm_container.add_or_skip_action("/videos", values.storage.videos, perms_config) %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do c1.healthcheck.set_test("curl", {"url": "http://localhost:80"}) %}
{% do tpl.portals.add_portal({"port": values.network.web_port}) %}

{{ tpl.render() | tojson }}
